// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8dvGa0jZi7oz53F03e0n1CeZ5obhBR0',
    appId: '1:1044133973521:web:dd8e2c80557632b841ebb0',
    messagingSenderId: '1044133973521',
    projectId: 'nutrisync-98850',
    authDomain: 'nutrisync-98850.firebaseapp.com',
    storageBucket: 'nutrisync-98850.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXGRXYqg6WPScFQy-C9htC-VI4IIyGJkw',
    appId: '1:1044133973521:android:b1392ddb92d5fee041ebb0',
    messagingSenderId: '1044133973521',
    projectId: 'nutrisync-98850',
    storageBucket: 'nutrisync-98850.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGlObZw7Orw5Gk8luUieC6o1LidlpTZw',
    appId: '1:1044133973521:ios:91e719c860d2d02441ebb0',
    messagingSenderId: '1044133973521',
    projectId: 'nutrisync-98850',
    storageBucket: 'nutrisync-98850.firebasestorage.app',
    androidClientId: '1044133973521-9ornrf483oni8sj9r4mvse31gq36u2hv.apps.googleusercontent.com',
    iosClientId: '1044133973521-jso7h31ievq1jsqdd8j2vo2n24n812dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGlObZw7Orw5Gk8luUieC6o1LidlpTZw',
    appId: '1:1044133973521:ios:91e719c860d2d02441ebb0',
    messagingSenderId: '1044133973521',
    projectId: 'nutrisync-98850',
    storageBucket: 'nutrisync-98850.firebasestorage.app',
    androidClientId: '1044133973521-9ornrf483oni8sj9r4mvse31gq36u2hv.apps.googleusercontent.com',
    iosClientId: '1044133973521-jso7h31ievq1jsqdd8j2vo2n24n812dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw8dvGa0jZi7oz53F03e0n1CeZ5obhBR0',
    appId: '1:1044133973521:web:b5559a68f930d8fc41ebb0',
    messagingSenderId: '1044133973521',
    projectId: 'nutrisync-98850',
    authDomain: 'nutrisync-98850.firebaseapp.com',
    storageBucket: 'nutrisync-98850.firebasestorage.app',
  );
}
